### ISSUE TITLE
Flashing on ubuntu

### ISSUE THREAD

**Issue by rigidsh** [greggersaurus/SteamControllerConfig#1]
If you will use  "cat new_firmware.bin > /mount/CRP\ DISABLD/firmware.bin" on ubuntu(or similar linux) firmware will be corrupted and controller will not start.

To prevent it, use command:
`dd conv=nocreat,notrunc oflag=direct bs=512 if=<path to your firmware> of=<path to sc flash>/firmware.bin`

**Comment by greggersaurus** [comment]
Thanks for passing this info along. I've been developing on OSX for this project and simply using "cat" works fine in that environment. I'll update my README and also make sure to reference AN11305 which details some additional caveats for anyone who might be running Windows.
