### ISSUE TITLE
Bluetooth on fauxcontroller

### ISSUE THREAD

**Issue by pcs3rd** [greggersaurus/SteamControllerConfig#12]
Is it possible?
EDIT: actually, would it be plausible to merge parts of the OSC firmware into this to adjust settings while plugged into a pc?

**Comment by greggersaurus** [comment]
No this is not possible. The FauxControllers project is targeted to run on the LPCXpresso11U37H Evaluation board OM13074 (https://www.nxp.com/design/microcontrollers-developer-resources/lpcxpresso-boards/lpcxpresso-board-for-lpc11u37h:OM13074). This board only has the LPC11U37H chip on it and not the nRF51822 which is used for Bluetooth communications on the SC. 

Please let me know if I'm misunderstanding your question.

**Comment by pcs3rd** [comment]
Nope, that was exactly the question! TBH my questions weren't exactly matching together, but bluetooth is impossible, but what about adjusting stuff like in the osc firmware

**Comment by greggersaurus** [comment]
You could definitely port over the OSC Firmware such that the DEV_BOARD_FW build would give you a console via USB on your PC. The only issue that any command related to external hardware interactions (e.g. the trackpads which we communicate with via SPI) wouldn't do much.

Would the reason for porting this work be that debugging on the LPCXpresso11U37H Evaluation board OM13074 would be easier? Or is there another reason I'm not seeing?
