### ISSUE TITLE
Attempting to convert a jingle on ubuntu results in the program hanging with high CPU usage 

### ISSUE THREAD

**Issue by djhorine** [greggersaurus/SteamControllerConfig#3]
OS: Ubuntu 19.04
CPU: AMD Athlon X4 860k
QT Creator: 4.9.1
QT: 5.12.3

The program launches from QT creator without any issues, but attempting to convert a jingle results in one of my CPU cores staying at 100% from the program and the program hanging. The process never finishes.

MusicXML I'm trying to use: https://musescore.com/user/124018/scores/133609 
I've tried other ones and the same result occurs.

![Terminal-2019-06-12-07:21:39](https://user-images.githubusercontent.com/47264981/59347628-2358d580-8ce3-11e9-8cf5-cbd4ea773eba.png)

EDIT: Fixed, I was using compressed musicxml files, not uncompressed.

**Comment by greggersaurus** [comment]
Reopening as this is something that should not be able to happen. 

Thanks for the detailed explanation and finding the root cause. I have reproduced the issue and should have a fix out soon to resolve this.
