### ISSUE TITLE
Switch pro steam 

### ISSUE THREAD

**Issue by ddziech** [greggersaurus/SteamControllerConfig#9]
If i use OpenSteamControllerNinSwitch.bin steam should detect controller?

**Comment by greggersaurus** [comment]
No Steam will not detect the controller in that state. When that firmware is loaded the controller will appear as a 3rd party wired Switch controller (https://store.powera.com/Product/1503255-Nintendo_Switch_Wired_Controller_Super_Mario_Edition?cat=CONSWITCH#frm%3DCONSWITCH%26p%3D40) and Steam does not have support for that controller.
